### PR TITLE
SEO fix for header

### LINKED ISSUE #412: SEO and Accessibility issue in header
Screenshot 2023-11-20 at 11 11 33 PM
Screenshot 2023-11-20 at 11 12 25 PM

### PR DESCRIPTION
**Pull request by hparwani2**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes #412 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com/
- Before: https://main--sunstar--hlxsites.hlx.live/
- After: https://issue-412--sunstar--hlxsites.hlx.live/

## Library

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. _cards_
- [ ] Documented in sidekick library

- [ ] New variations introduced in this PR
**Variation Name** :  For e.g. _cards (grid)_
- [ ] Documented in sidekick library

- [ ] New mixins introduced in this PR
**Mixin Name** :  For e.g. _compact, white_
- [ ] Documented in sidekick library

### CODE REVIEW

File: blocks/header/header.js [hunk 1]
```diff
@@ -38,6 +38,7 @@ async function decorateWebsitePicker(websitePicker) {
   });
 
   const a = document.createElement('a');
+  a.href = '#';
```
Comment (sdmcraft) [inline blocks/header/header.js:41]: On sunstar.com, the website picker is not an anchor element. Is there a reason we need to have it as an anchor tag?

File: blocks/header/header.js [hunk 2]
```diff
@@ -136,6 +137,7 @@ async function decorateLangPicker(langPicker) {
...
```
Comment (sdmcraft) [inline blocks/header/header.js:140]: Same question for lang picker, on original site it isn't an anchor while we have it as anchor.
