### PR TITLE
Fixing the bug for hightlight - /newsroom & /healthy-thinking pages a…

### LINKED ISSUE #387: Healthy thinking highlighted big articles disappeared
It looks like the big highlighted articles for each category disappeared: 

Edge delivery:
image

Current:
image

@sdmcraft

### PR DESCRIPTION
**Pull request by meejain**
…re showing correctly

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

#387 

Fixes #387 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com/healthy-thinking
- Before: https://main--sunstar--hlxsites.hlx.live/healthy-thinking
- After: https://issue387-highlight-bug--sunstar--hlxsites.hlx.live/healthy-thinking

## Library

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. _cards_
- [ ] Documented in sidekick library

- [ ] New variations introduced in this PR
**Variation Name** :  For e.g. _cards (grid)_
- [ ] Documented in sidekick library

- [ ] New mixins introduced in this PR
**Mixin Name** :  For e.g. _compact, white_
- [ ] Documented in sidekick library

### CODE REVIEW

**Comment by meejain** [comment]
Both https://issue387-highlight-bug--sunstar--hlxsites.hlx.live/healthy-thinking & https://issue387-highlight-bug--sunstar--hlxsites.hlx.live/newsroom pages are working fine.

File: blocks/highlight/highlight.js [hunk 1]
```diff
@@ -1,17 +1,18 @@
 export default async function decorate(block) {
   let spotlight = document.createElement('div');
+  const check = (block.classList.contains('feed-newsroom'));
```
Comment (sdmcraft) [inline blocks/highlight/highlight.js:3]: Nit:
```suggestion
  const hideSpotlight = (block.classList.contains('feed-newsroom'));
```
